# Generated by Django 6.0.1 on 2026-03-26 06:44

import django.db.models.deletion
import payouts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0005_donation_payout_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_ref', models.CharField(db_index=True, help_text='Frontend-generated donation ID string', max_length=128)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_name', models.CharField(blank=True, max_length=255)),
                ('recipient_address', models.CharField(max_length=255)),
                ('vault_address', models.CharField(blank=True, max_length=255)),
                ('payout_amount_satoshis', models.BigIntegerField()),
                ('coin', models.CharField(default='BCH', max_length=20)),
                ('interval_label', models.CharField(blank=True, max_length=50)),
                ('interval_blocks', models.PositiveIntegerField(default=1)),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('due_at', models.DateTimeField()),
                ('approval_token_hash', models.CharField(max_length=128, unique=True)),
                ('approval_expires_at', models.DateTimeField(default=payouts.models.default_expiry)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('txid', models.CharField(blank=True, max_length=255)),
                ('execution_error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('executed', 'Executed'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_approvals', to='donations.donation')),
            ],
            options={
                'verbose_name': 'Payout Approval',
                'verbose_name_plural': 'Payout Approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('email_sent', 'Email Sent'), ('approval_attempt', 'Approval Attempt'), ('approved', 'Approved'), ('execution_start', 'Execution Start'), ('executed', 'Executed'), ('execution_failed', 'Execution Failed'), ('expired', 'Expired'), ('rejected', 'Rejected')], max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payout_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payouts.payoutapproval')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payoutapproval',
            index=models.Index(fields=['donation_ref', 'status'], name='payouts_pay_donatio_34ea0f_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutapproval',
            index=models.Index(fields=['approval_token_hash'], name='payouts_pay_approva_e85f0d_idx'),
        ),
    ]
