# Generated by Django 6.0.1 on 2026-03-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutapproval',
            name='total_cycles',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
