# Generated by Django 5.2.11 on 2026-04-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_payoutapproval_total_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutapproval',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
