# Generated by Django 5.2.11 on 2026-04-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_allow_blank_donor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutapproval',
            name='txid',
            field=models.CharField(blank=True, help_text='64-char hex blockchain transaction hash', max_length=64),
        ),
    ]
