# Generated by Django 6.0.1 on 2026-04-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0008_donation_wallet_address_donation_wallet_user'),
        ('users', '0004_walletuser_balance_walletuser_chain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id_ref', models.CharField(db_index=True, help_text='Frontend-generated donationId', max_length=128, unique=True)),
                ('vault_address', models.CharField(db_index=True, max_length=255)),
                ('recipient_address', models.CharField(max_length=255)),
                ('funder_address', models.CharField(max_length=255)),
                ('withdrawal_satoshis', models.BigIntegerField()),
                ('deposit_satoshis', models.BigIntegerField(default=0)),
                ('interval_blocks', models.PositiveIntegerField()),
                ('interval_label', models.CharField(blank=True, max_length=50)),
                ('contract_params', models.JSONField(default=dict, help_text='recipientHash, funderHash')),
                ('payout_mode', models.CharField(default='smart', max_length=20)),
                ('coin', models.CharField(default='BCH', max_length=20)),
                ('network', models.CharField(default='chipnet', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('funded', 'Funded'), ('withdrawing', 'Withdrawing'), ('drained', 'Drained'), ('completed', 'Completed'), ('reclaimed', 'Reclaimed')], default='funded', max_length=20)),
                ('cycles_completed', models.PositiveIntegerField(default=0)),
                ('total_cycles', models.PositiveIntegerField(default=1)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('donor_name', models.CharField(blank=True, max_length=255)),
                ('cause', models.CharField(blank=True, max_length=255)),
                ('funding_txid', models.CharField(blank=True, max_length=64)),
                ('last_withdraw_txid', models.CharField(blank=True, max_length=64)),
                ('last_withdraw_at', models.DateTimeField(blank=True, null=True)),
                ('reclaim_txid', models.CharField(blank=True, max_length=64)),
                ('reclaimed_at', models.DateTimeField(blank=True, null=True)),
                ('reclaimed_amount', models.BigIntegerField(default=0)),
                ('reclaim_warning_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaults', to='donations.donation')),
                ('wallet_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaults', to='users.walletuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField()),
                ('txid', models.CharField(max_length=64)),
                ('amount_satoshis', models.BigIntegerField()),
                ('drained', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_cycles', to='vaults.vault')),
            ],
            options={
                'ordering': ['cycle_number'],
                'unique_together': {('vault', 'cycle_number')},
            },
        ),
    ]
