# Generated by Django 6.0.1 on 2026-04-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Nonprofit organization name', max_length=255),
        ),
    ]
