# Generated by Django 5.2.11 on 2026-03-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('recipient', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=16)),
                ('coin', models.CharField(default='BCH', max_length=20)),
                ('cause', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('donor_name', models.CharField(blank=True, max_length=255)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('donor_contact', models.CharField(blank=True, max_length=50)),
                ('explorer_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
