# Generated by Django 5.2.11 on 2026-03-16 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('nonprofits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='interval',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='nonprofit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='nonprofits.nonprofit'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['-timestamp'], name='donations_d_timesta_c04cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['txid'], name='donations_d_txid_52bc50_idx'),
        ),
    ]
