# Generated by Django 5.2.11 on 2026-03-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_interval_donation_nonprofit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='contract',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
