# Generated by Django 6.0.1 on 2026-03-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='explorer_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
