# Generated by Django 6.0.1 on 2026-03-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_donation_explorer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payout_mode',
            field=models.CharField(blank=True, default='smart', help_text='smart = auto-withdraw, inbox_approval = email approval required', max_length=20),
        ),
    ]
