# Generated by Django 5.2.11 on 2026-04-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation_payout_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='contract',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
