# Generated by Django 5.2.11 on 2026-04-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_expand_contract_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='interval_blocks',
            field=models.IntegerField(default=0),
        ),
    ]
