# Generated by Django 5.2.11 on 2026-04-08 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_add_interval_blocks'),
        ('users', '0002_walletuser_delete_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='wallet_address',
            field=models.CharField(blank=True, db_index=True, help_text='Donor wallet address (lowercase)', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='wallet_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='users.walletuser'),
        ),
    ]
