# Generated by Django 5.2.11 on 2026-04-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_donation_wallet_address_donation_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='reclaim_txid',
            field=models.CharField(blank=True, db_index=True, help_text='Transaction ID of reclaim/withdrawal', max_length=255),
        ),
    ]
