# Generated by Django 5.2.11 on 2026-03-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nonprofit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bch_address', models.CharField(db_index=True, max_length=255, unique=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('environment', 'Environment'), ('poverty', 'Poverty Alleviation'), ('animal_welfare', 'Animal Welfare'), ('arts_culture', 'Arts & Culture'), ('human_rights', 'Human Rights'), ('disaster_relief', 'Disaster Relief'), ('other', 'Other')], max_length=50)),
                ('logo_url', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_donations', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('donation_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Nonprofit Organization',
                'verbose_name_plural': 'Nonprofit Organizations',
                'ordering': ['-created_at'],
            },
        ),
    ]
