# Generated by Django 5.2.11 on 2026-03-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonprofit',
            name='category',
            field=models.CharField(choices=[('animals', 'Animals'), ('poverty', 'Poverty Alleviation'), ('children_youth', 'Children & Youth'), ('housing_humanitarian', 'Housing & Community Humanitarian Aid'), ('environment', 'Environment & Conservation')], max_length=50),
        ),
    ]
