# Generated by Django 6.0.1 on 2026-03-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(blank=True, default='', help_text='Name of the wallet or account (N/A if not available)', max_length=255)),
                ('wallet_address', models.CharField(db_index=True, help_text='Connected wallet address', max_length=255, unique=True)),
                ('first_connected', models.DateTimeField(auto_now_add=True)),
                ('last_connected', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
                'ordering': ['-last_connected'],
            },
        ),
    ]
