# Generated by Django 6.0.1 on 2026-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_walletuser_delete_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
