# Generated by Django 6.0.1 on 2026-04-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_walletuser_contact_walletuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='chain',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='namespace',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
